name: Semgrep

on:
  push:
    branches: [ "*" ]

jobs:
  semgrep:
    name: Scan
    permissions:
      contents: read # for actions/checkout to fetch code
      actions: read
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]') # Skip any PR created by dependabot to avoid permission issues
    steps:
      - name: Fetch project source with GitHub Actions Checkout.
        uses: actions/checkout@v3
      - name: Install jq
        run: apk add jq
      - name: Run semgrep
        run: |
          length=0
          for ruleFile in `ls semgrep_rules`;do 
            touch semgrep.sarif
            semgrep scan --sarif -o ${ruleFile%.*}.sarif --config semgrep_rules/${ruleFile} --metrics=off .
            if [ ${length} == 0 ];then
              mv ${ruleFile%.*}.sarif semgrep.sarif
            else
              jq '.runs[].tool[]' ${ruleFile%.*}.sarif  #| jq '. + .runs[].tool[]' semgrep.sarif  > semgrep1.sarif
              mv semgrep1.sarif semgrep.sarif
            fi    
            tempCounter=$((counter++))
          done 
      - name: Print final semgrep report
        run: cat semgrep.sarif         
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()