# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow file requires a free account on Semgrep.dev to
# manage rules, file ignores, notifications, and more.
#
# See https://semgrep.dev/docs

name: Semgrep

on:
  push:
    branches: [ "*" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "*" ]

jobs:
  semgrep:
    name: Scan
    permissions:
      contents: read # for actions/checkout to fetch code
      actions: read
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source with GitHub Actions Checkout.
      - uses: actions/checkout@v3
      - name: Install jq
        run: apk add jq
      - name: Run semgrep
        run: |
          # length=0
          for ruleFile in `ls semgrep_rules`;do 
            touch semgrep.sarif
            semgrep scan --sarif -o ${ruleFile%.*}.sarif --config semgrep_rules/${ruleFile} --metrics=off .
            if [ $length == 0 ];then
              # mv ${ruleFile%.*}.sarif semgrep.sarif
              echo first
            else
              # jq '.runs[].tool[]' ${ruleFile%.*}.sarif  #| jq '. + .runs[].tool[]' semgrep.sarif  > semgrep1.sarif
              # mv semgrep1.sarif semgrep.sarif
              echo $length
            fi    
            t=$((counter++))
          done          

      # Upload SARIF file generated in previous step
      # - name: Upload SARIF file for GitHub Advanced Security Dashboard
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: semgrep.sarif
      #   if: always()